define(["big.js"], (__WEBPACK_EXTERNAL_MODULE_big_js__) => { return /******/ (() => { // webpackBootstrap
/******/ 	var __webpack_modules__ = ({

/***/ "../../../../../../SHARED/GitHub/mendix-apps/LearnNow/javascriptsource/nanoflowcommons/actions/OpenMap.js":
/*!****************************************************************************************************************!*\
  !*** ../../../../../../SHARED/GitHub/mendix-apps/LearnNow/javascriptsource/nanoflowcommons/actions/OpenMap.js ***!
  \****************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "OpenMap": () => (/* binding */ OpenMap)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.


// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Opens a map application on your device or a web browser showing Google Maps.
 * @param {string} location - Can be either address, latitude/longitude (51.906, 4.488) or interest point.This field is required.
 * @returns {Promise.<boolean>}
 */
async function OpenMap(location) {
  // BEGIN USER CODE
  if (!location) {
    return Promise.reject(new Error("Input parameter 'Location' is required"));
  }
  location = encodeURIComponent(location);
  const iosUrl = `maps://maps.apple.com/?q=${location}`;
  const androidUrl = `geo:0,0?q=${location}`;
  const webUrl = `https://maps.google.com/maps?q=${location}`;
  // Native platform
  if (navigator && navigator.product === "ReactNative") {
    const Linking = (__webpack_require__(/*! react-native */ "?1252").Linking);
    const Platform = (__webpack_require__(/*! react-native */ "?1252").Platform);
    const url = Platform.select({
      ios: iosUrl,
      default: androidUrl
    });
    return Linking.canOpenURL(url).then(supported => {
      if (!supported) {
        return false;
      }
      return Linking.openURL(url).then(() => true);
    });
  }
  // Hybrid or mobile web platform
  if (window && window.navigator.userAgent) {
    // iOS platform
    if (/iPad|iPhone|iPod/i.test(window.navigator.userAgent)) {
      openUrl(iosUrl);
      return Promise.resolve(true);
    }
    // Android platform
    if (/android|sink/i.test(window.navigator.userAgent)) {
      openUrl(androidUrl);
      return Promise.resolve(true);
    }
  }
  // Desktop web or other platform
  if (window) {
    window.location.href = webUrl;
    return Promise.resolve(true);
  }
  return Promise.resolve(false);
  function openUrl(url) {
    // Hybrid platform
    if (window && window.cordova) {
      window.open(url, "_system");
    }
    // Mobile web platform
    if (window) {
      window.location.href = url;
    }
  }
  // END USER CODE
}

/***/ }),

/***/ "../../../../../../SHARED/GitHub/mendix-apps/LearnNow/javascriptsource/nanoflowcommons/actions/Share.js":
/*!**************************************************************************************************************!*\
  !*** ../../../../../../SHARED/GitHub/mendix-apps/LearnNow/javascriptsource/nanoflowcommons/actions/Share.js ***!
  \**************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "Share": () => (/* binding */ Share)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.


// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Action to invoke the native sharing mechanism of the device.
 * @param {string} url - The url to share.
 * @param {string} text - The text to share.
 * @param {string} title - An optional title for the message or url to share. Only some share targets use this value.
 * @returns {Promise.<boolean>}
 */
async function Share(url, text, title) {
  // BEGIN USER CODE
  if (!text && !url) {
    return Promise.reject(new Error("It is required to provide at least one of input parameters 'Text' and 'Url'"));
  }
  // Native platform
  // Documentation https://facebook.github.io/react-native/docs/share
  if (navigator && navigator.product === "ReactNative") {
    const RNShare = (__webpack_require__(/*! react-native */ "?1252").Share);
    const content = url && text ? {
      message: text + "\n" + url,
      title
    } : url ? {
      url,
      title
    } : {
      message: text,
      title
    };
    return RNShare.share(content).then(result => {
      if (result.action === RNShare.dismissedAction) {
        return false;
      }
      return true;
    });
  }
  // Web platform
  // Documentation https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share
  if (navigator && navigator.share) {
    return navigator.share({
      url,
      text,
      title
    }).then(() => true);
  }
  // Hybrid platform
  // Documentation https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin
  if (window && window.plugins && window.plugins.socialsharing) {
    return new Promise((resolve, reject) => {
      window.plugins.socialsharing.shareWithOptions({
        message: text,
        subject: title,
        url
      }, result => resolve(result.completed), errorMessage => reject(new Error(errorMessage)));
    });
  }
  if (document && document.location && document.location.protocol === "http:") {
    return Promise.reject(new Error("This action requires a secure https: connection"));
  }
  return Promise.reject(new Error("This action is not supported by this browser"));
  // END USER CODE
}

/***/ }),

/***/ "big.js":
/*!*************************!*\
  !*** external "big.js" ***!
  \*************************/
/***/ ((module) => {

"use strict";
module.exports = __WEBPACK_EXTERNAL_MODULE_big_js__;

/***/ }),

/***/ "?1252":
/*!*************************************!*\
  !*** react-native (ignored module) ***!
  \*************************************/
/***/ (() => {

/* empty */

/***/ })

/******/ 	});
/************************************************************************/
/******/ 	// The module cache
/******/ 	var __webpack_module_cache__ = {};
/******/ 	
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/ 		// Check if module is in cache
/******/ 		var cachedModule = __webpack_module_cache__[moduleId];
/******/ 		if (cachedModule !== undefined) {
/******/ 			return cachedModule.exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = __webpack_module_cache__[moduleId] = {
/******/ 			// no module.id needed
/******/ 			// no module.loaded needed
/******/ 			exports: {}
/******/ 		};
/******/ 	
/******/ 		// Execute the module function
/******/ 		__webpack_modules__[moduleId](module, module.exports, __webpack_require__);
/******/ 	
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/ 	
/************************************************************************/
/******/ 	/* webpack/runtime/compat get default export */
/******/ 	(() => {
/******/ 		// getDefaultExport function for compatibility with non-harmony modules
/******/ 		__webpack_require__.n = (module) => {
/******/ 			var getter = module && module.__esModule ?
/******/ 				() => (module['default']) :
/******/ 				() => (module);
/******/ 			__webpack_require__.d(getter, { a: getter });
/******/ 			return getter;
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/define property getters */
/******/ 	(() => {
/******/ 		// define getter functions for harmony exports
/******/ 		__webpack_require__.d = (exports, definition) => {
/******/ 			for(var key in definition) {
/******/ 				if(__webpack_require__.o(definition, key) && !__webpack_require__.o(exports, key)) {
/******/ 					Object.defineProperty(exports, key, { enumerable: true, get: definition[key] });
/******/ 				}
/******/ 			}
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/hasOwnProperty shorthand */
/******/ 	(() => {
/******/ 		__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/make namespace object */
/******/ 	(() => {
/******/ 		// define __esModule on exports
/******/ 		__webpack_require__.r = (exports) => {
/******/ 			if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 				Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 			}
/******/ 			Object.defineProperty(exports, '__esModule', { value: true });
/******/ 		};
/******/ 	})();
/******/ 	
/************************************************************************/
var __webpack_exports__ = {};
// This entry need to be wrapped in an IIFE because it need to be in strict mode.
(() => {
"use strict";
/*!****************************************************************************************!*\
  !*** ../../../../../../SHARED/GitHub/mendix-apps/LearnNow/deployment/tmp/jsactions.js ***!
  \****************************************************************************************/
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "NanoflowCommons$OpenMap": () => (/* binding */ NanoflowCommons$OpenMap),
/* harmony export */   "NanoflowCommons$Share": () => (/* binding */ NanoflowCommons$Share)
/* harmony export */ });
const NanoflowCommons$Share = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../SHARED/GitHub/mendix-apps/LearnNow/javascriptsource/nanoflowcommons/actions/Share */ "../../../../../../SHARED/GitHub/mendix-apps/LearnNow/javascriptsource/nanoflowcommons/actions/Share.js"))).Share;
const NanoflowCommons$OpenMap = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../SHARED/GitHub/mendix-apps/LearnNow/javascriptsource/nanoflowcommons/actions/OpenMap */ "../../../../../../SHARED/GitHub/mendix-apps/LearnNow/javascriptsource/nanoflowcommons/actions/OpenMap.js"))).OpenMap;
})();

/******/ 	return __webpack_exports__;
/******/ })()
;
});;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoianNhY3Rpb25zLmpzIiwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7QUFBQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUM2Qjs7QUFFN0I7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ08sZUFBZUMsT0FBTyxDQUFDQyxRQUFRLEVBQUU7RUFDdkM7RUFDRyxJQUFJLENBQUNBLFFBQVEsRUFBRTtJQUNYLE9BQU9DLE9BQU8sQ0FBQ0MsTUFBTSxDQUFDLElBQUlDLEtBQUssQ0FBQyx3Q0FBd0MsQ0FBQyxDQUFDO0VBQzlFO0VBQ0FILFFBQVEsR0FBR0ksa0JBQWtCLENBQUNKLFFBQVEsQ0FBQztFQUN2QyxNQUFNSyxNQUFNLEdBQUksNEJBQTJCTCxRQUFTLEVBQUM7RUFDckQsTUFBTU0sVUFBVSxHQUFJLGFBQVlOLFFBQVMsRUFBQztFQUMxQyxNQUFNTyxNQUFNLEdBQUksa0NBQWlDUCxRQUFTLEVBQUM7RUFDM0Q7RUFDQSxJQUFJUSxTQUFTLElBQUlBLFNBQVMsQ0FBQ0MsT0FBTyxLQUFLLGFBQWEsRUFBRTtJQUNsRCxNQUFNQyxPQUFPLEdBQUdDLDBEQUErQjtJQUMvQyxNQUFNQyxRQUFRLEdBQUdELDJEQUFnQztJQUNqRCxNQUFNRSxHQUFHLEdBQUdELFFBQVEsQ0FBQ0UsTUFBTSxDQUFDO01BQ3hCQyxHQUFHLEVBQUVWLE1BQU07TUFDWFcsT0FBTyxFQUFFVjtJQUNiLENBQUMsQ0FBQztJQUNGLE9BQU9JLE9BQU8sQ0FBQ08sVUFBVSxDQUFDSixHQUFHLENBQUMsQ0FBQ0ssSUFBSSxDQUFDQyxTQUFTLElBQUk7TUFDN0MsSUFBSSxDQUFDQSxTQUFTLEVBQUU7UUFDWixPQUFPLEtBQUs7TUFDaEI7TUFDQSxPQUFPVCxPQUFPLENBQUNVLE9BQU8sQ0FBQ1AsR0FBRyxDQUFDLENBQUNLLElBQUksQ0FBQyxNQUFNLElBQUksQ0FBQztJQUNoRCxDQUFDLENBQUM7RUFDTjtFQUNBO0VBQ0EsSUFBSUcsTUFBTSxJQUFJQSxNQUFNLENBQUNiLFNBQVMsQ0FBQ2MsU0FBUyxFQUFFO0lBQ3RDO0lBQ0EsSUFBSSxtQkFBbUIsQ0FBQ0MsSUFBSSxDQUFDRixNQUFNLENBQUNiLFNBQVMsQ0FBQ2MsU0FBUyxDQUFDLEVBQUU7TUFDdERFLE9BQU8sQ0FBQ25CLE1BQU0sQ0FBQztNQUNmLE9BQU9KLE9BQU8sQ0FBQ3dCLE9BQU8sQ0FBQyxJQUFJLENBQUM7SUFDaEM7SUFDQTtJQUNBLElBQUksZUFBZSxDQUFDRixJQUFJLENBQUNGLE1BQU0sQ0FBQ2IsU0FBUyxDQUFDYyxTQUFTLENBQUMsRUFBRTtNQUNsREUsT0FBTyxDQUFDbEIsVUFBVSxDQUFDO01BQ25CLE9BQU9MLE9BQU8sQ0FBQ3dCLE9BQU8sQ0FBQyxJQUFJLENBQUM7SUFDaEM7RUFDSjtFQUNBO0VBQ0EsSUFBSUosTUFBTSxFQUFFO0lBQ1JBLE1BQU0sQ0FBQ3JCLFFBQVEsQ0FBQzBCLElBQUksR0FBR25CLE1BQU07SUFDN0IsT0FBT04sT0FBTyxDQUFDd0IsT0FBTyxDQUFDLElBQUksQ0FBQztFQUNoQztFQUNBLE9BQU94QixPQUFPLENBQUN3QixPQUFPLENBQUMsS0FBSyxDQUFDO0VBQzdCLFNBQVNELE9BQU8sQ0FBQ1gsR0FBRyxFQUFFO0lBQ2xCO0lBQ0EsSUFBSVEsTUFBTSxJQUFJQSxNQUFNLENBQUNNLE9BQU8sRUFBRTtNQUMxQk4sTUFBTSxDQUFDTyxJQUFJLENBQUNmLEdBQUcsRUFBRSxTQUFTLENBQUM7SUFDL0I7SUFDQTtJQUNBLElBQUlRLE1BQU0sRUFBRTtNQUNSQSxNQUFNLENBQUNyQixRQUFRLENBQUMwQixJQUFJLEdBQUdiLEdBQUc7SUFDOUI7RUFDSjtFQUNIO0FBQ0Q7Ozs7Ozs7Ozs7Ozs7Ozs7O0FDdkVBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQzZCOztBQUU3QjtBQUNBOztBQUVBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ08sZUFBZWdCLEtBQUssQ0FBQ2hCLEdBQUcsRUFBRWlCLElBQUksRUFBRUMsS0FBSyxFQUFFO0VBQzdDO0VBQ0csSUFBSSxDQUFDRCxJQUFJLElBQUksQ0FBQ2pCLEdBQUcsRUFBRTtJQUNmLE9BQU9aLE9BQU8sQ0FBQ0MsTUFBTSxDQUFDLElBQUlDLEtBQUssQ0FBQyw2RUFBNkUsQ0FBQyxDQUFDO0VBQ25IO0VBQ0E7RUFDQTtFQUNBLElBQUlLLFNBQVMsSUFBSUEsU0FBUyxDQUFDQyxPQUFPLEtBQUssYUFBYSxFQUFFO0lBQ2xELE1BQU11QixPQUFPLEdBQUdyQix3REFBNkI7SUFDN0MsTUFBTXNCLE9BQU8sR0FBR3BCLEdBQUcsSUFBSWlCLElBQUksR0FBRztNQUFFSSxPQUFPLEVBQUVKLElBQUksR0FBRyxJQUFJLEdBQUdqQixHQUFHO01BQUVrQjtJQUFNLENBQUMsR0FBR2xCLEdBQUcsR0FBRztNQUFFQSxHQUFHO01BQUVrQjtJQUFNLENBQUMsR0FBRztNQUFFRyxPQUFPLEVBQUVKLElBQUk7TUFBRUM7SUFBTSxDQUFDO0lBQ3JILE9BQU9DLE9BQU8sQ0FBQ0csS0FBSyxDQUFDRixPQUFPLENBQUMsQ0FBQ2YsSUFBSSxDQUFDa0IsTUFBTSxJQUFJO01BQ3pDLElBQUlBLE1BQU0sQ0FBQ0MsTUFBTSxLQUFLTCxPQUFPLENBQUNNLGVBQWUsRUFBRTtRQUMzQyxPQUFPLEtBQUs7TUFDaEI7TUFDQSxPQUFPLElBQUk7SUFDZixDQUFDLENBQUM7RUFDTjtFQUNBO0VBQ0E7RUFDQSxJQUFJOUIsU0FBUyxJQUFJQSxTQUFTLENBQUMyQixLQUFLLEVBQUU7SUFDOUIsT0FBTzNCLFNBQVMsQ0FBQzJCLEtBQUssQ0FBQztNQUFFdEIsR0FBRztNQUFFaUIsSUFBSTtNQUFFQztJQUFNLENBQUMsQ0FBQyxDQUFDYixJQUFJLENBQUMsTUFBTSxJQUFJLENBQUM7RUFDakU7RUFDQTtFQUNBO0VBQ0EsSUFBSUcsTUFBTSxJQUFJQSxNQUFNLENBQUNrQixPQUFPLElBQUlsQixNQUFNLENBQUNrQixPQUFPLENBQUNDLGFBQWEsRUFBRTtJQUMxRCxPQUFPLElBQUl2QyxPQUFPLENBQUMsQ0FBQ3dCLE9BQU8sRUFBRXZCLE1BQU0sS0FBSztNQUNwQ21CLE1BQU0sQ0FBQ2tCLE9BQU8sQ0FBQ0MsYUFBYSxDQUFDQyxnQkFBZ0IsQ0FBQztRQUMxQ1AsT0FBTyxFQUFFSixJQUFJO1FBQ2JZLE9BQU8sRUFBRVgsS0FBSztRQUNkbEI7TUFDSixDQUFDLEVBQUV1QixNQUFNLElBQUlYLE9BQU8sQ0FBQ1csTUFBTSxDQUFDTyxTQUFTLENBQUMsRUFBRUMsWUFBWSxJQUFJMUMsTUFBTSxDQUFDLElBQUlDLEtBQUssQ0FBQ3lDLFlBQVksQ0FBQyxDQUFDLENBQUM7SUFDNUYsQ0FBQyxDQUFDO0VBQ047RUFDQSxJQUFJQyxRQUFRLElBQUlBLFFBQVEsQ0FBQzdDLFFBQVEsSUFBSTZDLFFBQVEsQ0FBQzdDLFFBQVEsQ0FBQzhDLFFBQVEsS0FBSyxPQUFPLEVBQUU7SUFDekUsT0FBTzdDLE9BQU8sQ0FBQ0MsTUFBTSxDQUFDLElBQUlDLEtBQUssQ0FBQyxpREFBaUQsQ0FBQyxDQUFDO0VBQ3ZGO0VBQ0EsT0FBT0YsT0FBTyxDQUFDQyxNQUFNLENBQUMsSUFBSUMsS0FBSyxDQUFDLDhDQUE4QyxDQUFDLENBQUM7RUFDbkY7QUFDRDs7Ozs7Ozs7Ozs7QUN6REE7Ozs7Ozs7Ozs7QUNBQTs7Ozs7O1VDQUE7VUFDQTs7VUFFQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTs7VUFFQTtVQUNBOztVQUVBO1VBQ0E7VUFDQTs7Ozs7V0N0QkE7V0FDQTtXQUNBO1dBQ0E7V0FDQTtXQUNBLGlDQUFpQyxXQUFXO1dBQzVDO1dBQ0E7Ozs7O1dDUEE7V0FDQTtXQUNBO1dBQ0E7V0FDQSx5Q0FBeUMsd0NBQXdDO1dBQ2pGO1dBQ0E7V0FDQTs7Ozs7V0NQQTs7Ozs7V0NBQTtXQUNBO1dBQ0E7V0FDQSx1REFBdUQsaUJBQWlCO1dBQ3hFO1dBQ0EsZ0RBQWdELGFBQWE7V0FDN0Q7Ozs7Ozs7Ozs7Ozs7Ozs7QUNOTyxNQUFNNEMscUJBQXFCLEdBQUcsWUFBWSxDQUFDLE1BQU0seVNBQThGLEVBQUVsQixLQUFLO0FBQ3RKLE1BQU1tQix1QkFBdUIsR0FBRyxZQUFZLENBQUMsTUFBTSw2U0FBZ0csRUFBRWpELE9BQU8sQyIsInNvdXJjZXMiOlsid2VicGFjazovLy8uLi8uLi8uLi8uLi8uLi8uLi9TSEFSRUQvR2l0SHViL21lbmRpeC1hcHBzL0xlYXJuTm93L2phdmFzY3JpcHRzb3VyY2UvbmFub2Zsb3djb21tb25zL2FjdGlvbnMvT3Blbk1hcC5qcyIsIndlYnBhY2s6Ly8vLi4vLi4vLi4vLi4vLi4vLi4vU0hBUkVEL0dpdEh1Yi9tZW5kaXgtYXBwcy9MZWFybk5vdy9qYXZhc2NyaXB0c291cmNlL25hbm9mbG93Y29tbW9ucy9hY3Rpb25zL1NoYXJlLmpzIiwid2VicGFjazovLy9leHRlcm5hbCBhbWQgXCJiaWcuanNcIiIsIndlYnBhY2s6Ly8vcmVhY3QtbmF0aXZlIiwid2VicGFjazovLy93ZWJwYWNrL2Jvb3RzdHJhcCIsIndlYnBhY2s6Ly8vd2VicGFjay9ydW50aW1lL2NvbXBhdCBnZXQgZGVmYXVsdCBleHBvcnQiLCJ3ZWJwYWNrOi8vL3dlYnBhY2svcnVudGltZS9kZWZpbmUgcHJvcGVydHkgZ2V0dGVycyIsIndlYnBhY2s6Ly8vd2VicGFjay9ydW50aW1lL2hhc093blByb3BlcnR5IHNob3J0aGFuZCIsIndlYnBhY2s6Ly8vd2VicGFjay9ydW50aW1lL21ha2UgbmFtZXNwYWNlIG9iamVjdCIsIndlYnBhY2s6Ly8vLi4vLi4vLi4vLi4vLi4vLi4vU0hBUkVEL0dpdEh1Yi9tZW5kaXgtYXBwcy9MZWFybk5vdy9kZXBsb3ltZW50L3RtcC9qc2FjdGlvbnMuanMiXSwic291cmNlc0NvbnRlbnQiOlsiLy8gVGhpcyBmaWxlIHdhcyBnZW5lcmF0ZWQgYnkgTWVuZGl4IFN0dWRpbyBQcm8uXHJcbi8vXHJcbi8vIFdBUk5JTkc6IE9ubHkgdGhlIGZvbGxvd2luZyBjb2RlIHdpbGwgYmUgcmV0YWluZWQgd2hlbiBhY3Rpb25zIGFyZSByZWdlbmVyYXRlZDpcclxuLy8gLSB0aGUgaW1wb3J0IGxpc3RcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIFVTRVIgQ09ERSBhbmQgRU5EIFVTRVIgQ09ERVxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gRVhUUkEgQ09ERSBhbmQgRU5EIEVYVFJBIENPREVcclxuLy8gT3RoZXIgY29kZSB5b3Ugd3JpdGUgd2lsbCBiZSBsb3N0IHRoZSBuZXh0IHRpbWUgeW91IGRlcGxveSB0aGUgcHJvamVjdC5cclxuaW1wb3J0IHsgQmlnIH0gZnJvbSBcImJpZy5qc1wiO1xyXG5cclxuLy8gQkVHSU4gRVhUUkEgQ09ERVxyXG4vLyBFTkQgRVhUUkEgQ09ERVxyXG5cclxuLyoqXHJcbiAqIE9wZW5zIGEgbWFwIGFwcGxpY2F0aW9uIG9uIHlvdXIgZGV2aWNlIG9yIGEgd2ViIGJyb3dzZXIgc2hvd2luZyBHb29nbGUgTWFwcy5cclxuICogQHBhcmFtIHtzdHJpbmd9IGxvY2F0aW9uIC0gQ2FuIGJlIGVpdGhlciBhZGRyZXNzLCBsYXRpdHVkZS9sb25naXR1ZGUgKDUxLjkwNiwgNC40ODgpIG9yIGludGVyZXN0IHBvaW50LlRoaXMgZmllbGQgaXMgcmVxdWlyZWQuXHJcbiAqIEByZXR1cm5zIHtQcm9taXNlLjxib29sZWFuPn1cclxuICovXHJcbmV4cG9ydCBhc3luYyBmdW5jdGlvbiBPcGVuTWFwKGxvY2F0aW9uKSB7XHJcblx0Ly8gQkVHSU4gVVNFUiBDT0RFXHJcbiAgICBpZiAoIWxvY2F0aW9uKSB7XHJcbiAgICAgICAgcmV0dXJuIFByb21pc2UucmVqZWN0KG5ldyBFcnJvcihcIklucHV0IHBhcmFtZXRlciAnTG9jYXRpb24nIGlzIHJlcXVpcmVkXCIpKTtcclxuICAgIH1cclxuICAgIGxvY2F0aW9uID0gZW5jb2RlVVJJQ29tcG9uZW50KGxvY2F0aW9uKTtcclxuICAgIGNvbnN0IGlvc1VybCA9IGBtYXBzOi8vbWFwcy5hcHBsZS5jb20vP3E9JHtsb2NhdGlvbn1gO1xyXG4gICAgY29uc3QgYW5kcm9pZFVybCA9IGBnZW86MCwwP3E9JHtsb2NhdGlvbn1gO1xyXG4gICAgY29uc3Qgd2ViVXJsID0gYGh0dHBzOi8vbWFwcy5nb29nbGUuY29tL21hcHM/cT0ke2xvY2F0aW9ufWA7XHJcbiAgICAvLyBOYXRpdmUgcGxhdGZvcm1cclxuICAgIGlmIChuYXZpZ2F0b3IgJiYgbmF2aWdhdG9yLnByb2R1Y3QgPT09IFwiUmVhY3ROYXRpdmVcIikge1xyXG4gICAgICAgIGNvbnN0IExpbmtpbmcgPSByZXF1aXJlKFwicmVhY3QtbmF0aXZlXCIpLkxpbmtpbmc7XHJcbiAgICAgICAgY29uc3QgUGxhdGZvcm0gPSByZXF1aXJlKFwicmVhY3QtbmF0aXZlXCIpLlBsYXRmb3JtO1xyXG4gICAgICAgIGNvbnN0IHVybCA9IFBsYXRmb3JtLnNlbGVjdCh7XHJcbiAgICAgICAgICAgIGlvczogaW9zVXJsLFxyXG4gICAgICAgICAgICBkZWZhdWx0OiBhbmRyb2lkVXJsXHJcbiAgICAgICAgfSk7XHJcbiAgICAgICAgcmV0dXJuIExpbmtpbmcuY2FuT3BlblVSTCh1cmwpLnRoZW4oc3VwcG9ydGVkID0+IHtcclxuICAgICAgICAgICAgaWYgKCFzdXBwb3J0ZWQpIHtcclxuICAgICAgICAgICAgICAgIHJldHVybiBmYWxzZTtcclxuICAgICAgICAgICAgfVxyXG4gICAgICAgICAgICByZXR1cm4gTGlua2luZy5vcGVuVVJMKHVybCkudGhlbigoKSA9PiB0cnVlKTtcclxuICAgICAgICB9KTtcclxuICAgIH1cclxuICAgIC8vIEh5YnJpZCBvciBtb2JpbGUgd2ViIHBsYXRmb3JtXHJcbiAgICBpZiAod2luZG93ICYmIHdpbmRvdy5uYXZpZ2F0b3IudXNlckFnZW50KSB7XHJcbiAgICAgICAgLy8gaU9TIHBsYXRmb3JtXHJcbiAgICAgICAgaWYgKC9pUGFkfGlQaG9uZXxpUG9kL2kudGVzdCh3aW5kb3cubmF2aWdhdG9yLnVzZXJBZ2VudCkpIHtcclxuICAgICAgICAgICAgb3BlblVybChpb3NVcmwpO1xyXG4gICAgICAgICAgICByZXR1cm4gUHJvbWlzZS5yZXNvbHZlKHRydWUpO1xyXG4gICAgICAgIH1cclxuICAgICAgICAvLyBBbmRyb2lkIHBsYXRmb3JtXHJcbiAgICAgICAgaWYgKC9hbmRyb2lkfHNpbmsvaS50ZXN0KHdpbmRvdy5uYXZpZ2F0b3IudXNlckFnZW50KSkge1xyXG4gICAgICAgICAgICBvcGVuVXJsKGFuZHJvaWRVcmwpO1xyXG4gICAgICAgICAgICByZXR1cm4gUHJvbWlzZS5yZXNvbHZlKHRydWUpO1xyXG4gICAgICAgIH1cclxuICAgIH1cclxuICAgIC8vIERlc2t0b3Agd2ViIG9yIG90aGVyIHBsYXRmb3JtXHJcbiAgICBpZiAod2luZG93KSB7XHJcbiAgICAgICAgd2luZG93LmxvY2F0aW9uLmhyZWYgPSB3ZWJVcmw7XHJcbiAgICAgICAgcmV0dXJuIFByb21pc2UucmVzb2x2ZSh0cnVlKTtcclxuICAgIH1cclxuICAgIHJldHVybiBQcm9taXNlLnJlc29sdmUoZmFsc2UpO1xyXG4gICAgZnVuY3Rpb24gb3BlblVybCh1cmwpIHtcclxuICAgICAgICAvLyBIeWJyaWQgcGxhdGZvcm1cclxuICAgICAgICBpZiAod2luZG93ICYmIHdpbmRvdy5jb3Jkb3ZhKSB7XHJcbiAgICAgICAgICAgIHdpbmRvdy5vcGVuKHVybCwgXCJfc3lzdGVtXCIpO1xyXG4gICAgICAgIH1cclxuICAgICAgICAvLyBNb2JpbGUgd2ViIHBsYXRmb3JtXHJcbiAgICAgICAgaWYgKHdpbmRvdykge1xyXG4gICAgICAgICAgICB3aW5kb3cubG9jYXRpb24uaHJlZiA9IHVybDtcclxuICAgICAgICB9XHJcbiAgICB9XHJcblx0Ly8gRU5EIFVTRVIgQ09ERVxyXG59XHJcbiIsIi8vIFRoaXMgZmlsZSB3YXMgZ2VuZXJhdGVkIGJ5IE1lbmRpeCBTdHVkaW8gUHJvLlxyXG4vL1xyXG4vLyBXQVJOSU5HOiBPbmx5IHRoZSBmb2xsb3dpbmcgY29kZSB3aWxsIGJlIHJldGFpbmVkIHdoZW4gYWN0aW9ucyBhcmUgcmVnZW5lcmF0ZWQ6XHJcbi8vIC0gdGhlIGltcG9ydCBsaXN0XHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBVU0VSIENPREUgYW5kIEVORCBVU0VSIENPREVcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIEVYVFJBIENPREUgYW5kIEVORCBFWFRSQSBDT0RFXHJcbi8vIE90aGVyIGNvZGUgeW91IHdyaXRlIHdpbGwgYmUgbG9zdCB0aGUgbmV4dCB0aW1lIHlvdSBkZXBsb3kgdGhlIHByb2plY3QuXHJcbmltcG9ydCB7IEJpZyB9IGZyb20gXCJiaWcuanNcIjtcclxuXHJcbi8vIEJFR0lOIEVYVFJBIENPREVcclxuLy8gRU5EIEVYVFJBIENPREVcclxuXHJcbi8qKlxyXG4gKiBBY3Rpb24gdG8gaW52b2tlIHRoZSBuYXRpdmUgc2hhcmluZyBtZWNoYW5pc20gb2YgdGhlIGRldmljZS5cclxuICogQHBhcmFtIHtzdHJpbmd9IHVybCAtIFRoZSB1cmwgdG8gc2hhcmUuXHJcbiAqIEBwYXJhbSB7c3RyaW5nfSB0ZXh0IC0gVGhlIHRleHQgdG8gc2hhcmUuXHJcbiAqIEBwYXJhbSB7c3RyaW5nfSB0aXRsZSAtIEFuIG9wdGlvbmFsIHRpdGxlIGZvciB0aGUgbWVzc2FnZSBvciB1cmwgdG8gc2hhcmUuIE9ubHkgc29tZSBzaGFyZSB0YXJnZXRzIHVzZSB0aGlzIHZhbHVlLlxyXG4gKiBAcmV0dXJucyB7UHJvbWlzZS48Ym9vbGVhbj59XHJcbiAqL1xyXG5leHBvcnQgYXN5bmMgZnVuY3Rpb24gU2hhcmUodXJsLCB0ZXh0LCB0aXRsZSkge1xyXG5cdC8vIEJFR0lOIFVTRVIgQ09ERVxyXG4gICAgaWYgKCF0ZXh0ICYmICF1cmwpIHtcclxuICAgICAgICByZXR1cm4gUHJvbWlzZS5yZWplY3QobmV3IEVycm9yKFwiSXQgaXMgcmVxdWlyZWQgdG8gcHJvdmlkZSBhdCBsZWFzdCBvbmUgb2YgaW5wdXQgcGFyYW1ldGVycyAnVGV4dCcgYW5kICdVcmwnXCIpKTtcclxuICAgIH1cclxuICAgIC8vIE5hdGl2ZSBwbGF0Zm9ybVxyXG4gICAgLy8gRG9jdW1lbnRhdGlvbiBodHRwczovL2ZhY2Vib29rLmdpdGh1Yi5pby9yZWFjdC1uYXRpdmUvZG9jcy9zaGFyZVxyXG4gICAgaWYgKG5hdmlnYXRvciAmJiBuYXZpZ2F0b3IucHJvZHVjdCA9PT0gXCJSZWFjdE5hdGl2ZVwiKSB7XHJcbiAgICAgICAgY29uc3QgUk5TaGFyZSA9IHJlcXVpcmUoXCJyZWFjdC1uYXRpdmVcIikuU2hhcmU7XHJcbiAgICAgICAgY29uc3QgY29udGVudCA9IHVybCAmJiB0ZXh0ID8geyBtZXNzYWdlOiB0ZXh0ICsgXCJcXG5cIiArIHVybCwgdGl0bGUgfSA6IHVybCA/IHsgdXJsLCB0aXRsZSB9IDogeyBtZXNzYWdlOiB0ZXh0LCB0aXRsZSB9O1xyXG4gICAgICAgIHJldHVybiBSTlNoYXJlLnNoYXJlKGNvbnRlbnQpLnRoZW4ocmVzdWx0ID0+IHtcclxuICAgICAgICAgICAgaWYgKHJlc3VsdC5hY3Rpb24gPT09IFJOU2hhcmUuZGlzbWlzc2VkQWN0aW9uKSB7XHJcbiAgICAgICAgICAgICAgICByZXR1cm4gZmFsc2U7XHJcbiAgICAgICAgICAgIH1cclxuICAgICAgICAgICAgcmV0dXJuIHRydWU7XHJcbiAgICAgICAgfSk7XHJcbiAgICB9XHJcbiAgICAvLyBXZWIgcGxhdGZvcm1cclxuICAgIC8vIERvY3VtZW50YXRpb24gaHR0cHM6Ly9kZXZlbG9wZXIubW96aWxsYS5vcmcvZW4tVVMvZG9jcy9XZWIvQVBJL05hdmlnYXRvci9zaGFyZVxyXG4gICAgaWYgKG5hdmlnYXRvciAmJiBuYXZpZ2F0b3Iuc2hhcmUpIHtcclxuICAgICAgICByZXR1cm4gbmF2aWdhdG9yLnNoYXJlKHsgdXJsLCB0ZXh0LCB0aXRsZSB9KS50aGVuKCgpID0+IHRydWUpO1xyXG4gICAgfVxyXG4gICAgLy8gSHlicmlkIHBsYXRmb3JtXHJcbiAgICAvLyBEb2N1bWVudGF0aW9uIGh0dHBzOi8vZ2l0aHViLmNvbS9FZGR5VmVyYnJ1Z2dlbi9Tb2NpYWxTaGFyaW5nLVBob25lR2FwLVBsdWdpblxyXG4gICAgaWYgKHdpbmRvdyAmJiB3aW5kb3cucGx1Z2lucyAmJiB3aW5kb3cucGx1Z2lucy5zb2NpYWxzaGFyaW5nKSB7XHJcbiAgICAgICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcclxuICAgICAgICAgICAgd2luZG93LnBsdWdpbnMuc29jaWFsc2hhcmluZy5zaGFyZVdpdGhPcHRpb25zKHtcclxuICAgICAgICAgICAgICAgIG1lc3NhZ2U6IHRleHQsXHJcbiAgICAgICAgICAgICAgICBzdWJqZWN0OiB0aXRsZSxcclxuICAgICAgICAgICAgICAgIHVybFxyXG4gICAgICAgICAgICB9LCByZXN1bHQgPT4gcmVzb2x2ZShyZXN1bHQuY29tcGxldGVkKSwgZXJyb3JNZXNzYWdlID0+IHJlamVjdChuZXcgRXJyb3IoZXJyb3JNZXNzYWdlKSkpO1xyXG4gICAgICAgIH0pO1xyXG4gICAgfVxyXG4gICAgaWYgKGRvY3VtZW50ICYmIGRvY3VtZW50LmxvY2F0aW9uICYmIGRvY3VtZW50LmxvY2F0aW9uLnByb3RvY29sID09PSBcImh0dHA6XCIpIHtcclxuICAgICAgICByZXR1cm4gUHJvbWlzZS5yZWplY3QobmV3IEVycm9yKFwiVGhpcyBhY3Rpb24gcmVxdWlyZXMgYSBzZWN1cmUgaHR0cHM6IGNvbm5lY3Rpb25cIikpO1xyXG4gICAgfVxyXG4gICAgcmV0dXJuIFByb21pc2UucmVqZWN0KG5ldyBFcnJvcihcIlRoaXMgYWN0aW9uIGlzIG5vdCBzdXBwb3J0ZWQgYnkgdGhpcyBicm93c2VyXCIpKTtcclxuXHQvLyBFTkQgVVNFUiBDT0RFXHJcbn1cclxuIiwibW9kdWxlLmV4cG9ydHMgPSBfX1dFQlBBQ0tfRVhURVJOQUxfTU9EVUxFX2JpZ19qc19fOyIsIi8qIGVtcHR5ICovIiwiLy8gVGhlIG1vZHVsZSBjYWNoZVxudmFyIF9fd2VicGFja19tb2R1bGVfY2FjaGVfXyA9IHt9O1xuXG4vLyBUaGUgcmVxdWlyZSBmdW5jdGlvblxuZnVuY3Rpb24gX193ZWJwYWNrX3JlcXVpcmVfXyhtb2R1bGVJZCkge1xuXHQvLyBDaGVjayBpZiBtb2R1bGUgaXMgaW4gY2FjaGVcblx0dmFyIGNhY2hlZE1vZHVsZSA9IF9fd2VicGFja19tb2R1bGVfY2FjaGVfX1ttb2R1bGVJZF07XG5cdGlmIChjYWNoZWRNb2R1bGUgIT09IHVuZGVmaW5lZCkge1xuXHRcdHJldHVybiBjYWNoZWRNb2R1bGUuZXhwb3J0cztcblx0fVxuXHQvLyBDcmVhdGUgYSBuZXcgbW9kdWxlIChhbmQgcHV0IGl0IGludG8gdGhlIGNhY2hlKVxuXHR2YXIgbW9kdWxlID0gX193ZWJwYWNrX21vZHVsZV9jYWNoZV9fW21vZHVsZUlkXSA9IHtcblx0XHQvLyBubyBtb2R1bGUuaWQgbmVlZGVkXG5cdFx0Ly8gbm8gbW9kdWxlLmxvYWRlZCBuZWVkZWRcblx0XHRleHBvcnRzOiB7fVxuXHR9O1xuXG5cdC8vIEV4ZWN1dGUgdGhlIG1vZHVsZSBmdW5jdGlvblxuXHRfX3dlYnBhY2tfbW9kdWxlc19fW21vZHVsZUlkXShtb2R1bGUsIG1vZHVsZS5leHBvcnRzLCBfX3dlYnBhY2tfcmVxdWlyZV9fKTtcblxuXHQvLyBSZXR1cm4gdGhlIGV4cG9ydHMgb2YgdGhlIG1vZHVsZVxuXHRyZXR1cm4gbW9kdWxlLmV4cG9ydHM7XG59XG5cbiIsIi8vIGdldERlZmF1bHRFeHBvcnQgZnVuY3Rpb24gZm9yIGNvbXBhdGliaWxpdHkgd2l0aCBub24taGFybW9ueSBtb2R1bGVzXG5fX3dlYnBhY2tfcmVxdWlyZV9fLm4gPSAobW9kdWxlKSA9PiB7XG5cdHZhciBnZXR0ZXIgPSBtb2R1bGUgJiYgbW9kdWxlLl9fZXNNb2R1bGUgP1xuXHRcdCgpID0+IChtb2R1bGVbJ2RlZmF1bHQnXSkgOlxuXHRcdCgpID0+IChtb2R1bGUpO1xuXHRfX3dlYnBhY2tfcmVxdWlyZV9fLmQoZ2V0dGVyLCB7IGE6IGdldHRlciB9KTtcblx0cmV0dXJuIGdldHRlcjtcbn07IiwiLy8gZGVmaW5lIGdldHRlciBmdW5jdGlvbnMgZm9yIGhhcm1vbnkgZXhwb3J0c1xuX193ZWJwYWNrX3JlcXVpcmVfXy5kID0gKGV4cG9ydHMsIGRlZmluaXRpb24pID0+IHtcblx0Zm9yKHZhciBrZXkgaW4gZGVmaW5pdGlvbikge1xuXHRcdGlmKF9fd2VicGFja19yZXF1aXJlX18ubyhkZWZpbml0aW9uLCBrZXkpICYmICFfX3dlYnBhY2tfcmVxdWlyZV9fLm8oZXhwb3J0cywga2V5KSkge1xuXHRcdFx0T2JqZWN0LmRlZmluZVByb3BlcnR5KGV4cG9ydHMsIGtleSwgeyBlbnVtZXJhYmxlOiB0cnVlLCBnZXQ6IGRlZmluaXRpb25ba2V5XSB9KTtcblx0XHR9XG5cdH1cbn07IiwiX193ZWJwYWNrX3JlcXVpcmVfXy5vID0gKG9iaiwgcHJvcCkgPT4gKE9iamVjdC5wcm90b3R5cGUuaGFzT3duUHJvcGVydHkuY2FsbChvYmosIHByb3ApKSIsIi8vIGRlZmluZSBfX2VzTW9kdWxlIG9uIGV4cG9ydHNcbl9fd2VicGFja19yZXF1aXJlX18uciA9IChleHBvcnRzKSA9PiB7XG5cdGlmKHR5cGVvZiBTeW1ib2wgIT09ICd1bmRlZmluZWQnICYmIFN5bWJvbC50b1N0cmluZ1RhZykge1xuXHRcdE9iamVjdC5kZWZpbmVQcm9wZXJ0eShleHBvcnRzLCBTeW1ib2wudG9TdHJpbmdUYWcsIHsgdmFsdWU6ICdNb2R1bGUnIH0pO1xuXHR9XG5cdE9iamVjdC5kZWZpbmVQcm9wZXJ0eShleHBvcnRzLCAnX19lc01vZHVsZScsIHsgdmFsdWU6IHRydWUgfSk7XG59OyIsImV4cG9ydCBjb25zdCBOYW5vZmxvd0NvbW1vbnMkU2hhcmUgPSBhc3luYyAoKSA9PiAoYXdhaXQgaW1wb3J0KFwiRTovU0hBUkVEL0dpdEh1Yi9tZW5kaXgtYXBwcy9MZWFybk5vdy9qYXZhc2NyaXB0c291cmNlL25hbm9mbG93Y29tbW9ucy9hY3Rpb25zL1NoYXJlXCIpKS5TaGFyZTtcbmV4cG9ydCBjb25zdCBOYW5vZmxvd0NvbW1vbnMkT3Blbk1hcCA9IGFzeW5jICgpID0+IChhd2FpdCBpbXBvcnQoXCJFOi9TSEFSRUQvR2l0SHViL21lbmRpeC1hcHBzL0xlYXJuTm93L2phdmFzY3JpcHRzb3VyY2UvbmFub2Zsb3djb21tb25zL2FjdGlvbnMvT3Blbk1hcFwiKSkuT3Blbk1hcDtcbiJdLCJuYW1lcyI6WyJCaWciLCJPcGVuTWFwIiwibG9jYXRpb24iLCJQcm9taXNlIiwicmVqZWN0IiwiRXJyb3IiLCJlbmNvZGVVUklDb21wb25lbnQiLCJpb3NVcmwiLCJhbmRyb2lkVXJsIiwid2ViVXJsIiwibmF2aWdhdG9yIiwicHJvZHVjdCIsIkxpbmtpbmciLCJyZXF1aXJlIiwiUGxhdGZvcm0iLCJ1cmwiLCJzZWxlY3QiLCJpb3MiLCJkZWZhdWx0IiwiY2FuT3BlblVSTCIsInRoZW4iLCJzdXBwb3J0ZWQiLCJvcGVuVVJMIiwid2luZG93IiwidXNlckFnZW50IiwidGVzdCIsIm9wZW5VcmwiLCJyZXNvbHZlIiwiaHJlZiIsImNvcmRvdmEiLCJvcGVuIiwiU2hhcmUiLCJ0ZXh0IiwidGl0bGUiLCJSTlNoYXJlIiwiY29udGVudCIsIm1lc3NhZ2UiLCJzaGFyZSIsInJlc3VsdCIsImFjdGlvbiIsImRpc21pc3NlZEFjdGlvbiIsInBsdWdpbnMiLCJzb2NpYWxzaGFyaW5nIiwic2hhcmVXaXRoT3B0aW9ucyIsInN1YmplY3QiLCJjb21wbGV0ZWQiLCJlcnJvck1lc3NhZ2UiLCJkb2N1bWVudCIsInByb3RvY29sIiwiTmFub2Zsb3dDb21tb25zJFNoYXJlIiwiTmFub2Zsb3dDb21tb25zJE9wZW5NYXAiXSwic291cmNlUm9vdCI6IiJ9